# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poroj', models.FloatField()),
                ('malporoj', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Radiko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radikaro', models.CharField(max_length=200)),
                ('poroj', models.FloatField()),
                ('malporoj', models.FloatField()),
                ('oficialeco', models.CharField(max_length=2)),
                ('duolingeco', models.BooleanField(default=False)),
                ('rango', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='propono',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponojDe', to='vortaro.Radiko'),
        ),
        migrations.AddField(
            model_name='propono',
            name='por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponoj', to='vortaro.Radiko'),
        ),
    ]
