# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortaro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiko',
            name='malporoj',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='radiko',
            name='oficialeco',
            field=models.CharField(default='X', max_length=2),
        ),
        migrations.AlterField(
            model_name='radiko',
            name='poroj',
            field=models.FloatField(default=0),
        ),
    ]
