# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vortaro', '0003_auto_20170122_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiko',
            old_name='rango',
            new_name='oftecrango',
        ),
    ]
