# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortaro', '0004_auto_20170122_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiko',
            name='eraro',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
