# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortaro', '0005_auto_20170124_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiko',
            name='plendoj',
            field=models.IntegerField(default=0),
        ),
    ]
