# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortaro', '0006_radiko_plendoj'),
    ]

    operations = [
        migrations.AddField(
            model_name='propono',
            name='eraro',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='propono',
            name='plendoj',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propono',
            name='malporoj',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='propono',
            name='poroj',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='radiko',
            name='eraro',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.RemoveField(
            model_name='propono',
            name='per',
        ),
        migrations.AlterUniqueTogether(
            name='propono',
            unique_together=set([('por', 'eraro')]),
        ),
    ]
