# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortaro', '0007_auto_20170128_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='propono',
            name='boneco',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='radiko',
            name='boneco',
            field=models.FloatField(default=0.5),
        ),
    ]
